package ox.fzer0x.snakeloader

import android.content.Context
import android.util.Log
import ox.fzer0x.snakeloader.utils.ShellExecutor
import java.io.File

class StealthConfigManager(private val context: Context, private val settings: SettingsManager) {
    companion object {
        private const val TAG = "StealthConfigManager"
        const val BASE_STEALTH_PATH = "/data/adb/reshift"
        const val LEGACY_BASE_PATH = "/data/local/tmp"
        
        const val DEFAULT_FRIDA_SERVER = "frida-server"
        const val DEFAULT_FRIDA_INJECT = "frida-inject"
        const val DEFAULT_FRIDA_CLI = "frida"
    }

    fun getBinaryName(default: String): String {
        if (!settings.isStealthModeEnabled) return default
        
        val type = when {
            default.contains("server") -> "server"
            default.contains("inject") -> "inject"
            default.contains("frida") -> "cli"
            else -> "default"
        }
        
        var name = when (type) {
            "server" -> settings.randomizedServerName
            "inject" -> settings.randomizedInjectName
            "cli" -> settings.randomizedCliName
            else -> settings.randomizedBinaryName
        }
        
        if (name.isEmpty()) {
            val allowedChars = ('a'..'z') + ('0'..'9')
            name = (1..8).map { allowedChars.random() }.joinToString("")
            when (type) {
                "server" -> settings.randomizedServerName = name
                "inject" -> settings.randomizedInjectName = name
                "cli" -> settings.randomizedCliName = name
                else -> settings.randomizedBinaryName = name
            }
            Log.d(TAG, "Generated new stealth $type binary name: $name")
        }
        return name
    }

    fun getActivePort(): Int {
        if (!settings.isStealthModeEnabled) return 27042
        
        var port = settings.randomizedPort
        if (port == 0) {
            port = (30000..60000).random()
            settings.randomizedPort = port
            Log.d(TAG, "Generated new stealth port: $port")
        }
        return port
    }

    fun getBasePath(): String {
        return if (settings.isStealthModeEnabled) BASE_STEALTH_PATH else LEGACY_BASE_PATH
    }

    fun getActiveServerPath(): String = "${getBasePath()}/${getBinaryName(DEFAULT_FRIDA_SERVER)}"
    fun getActiveInjectPath(): String = "${getBasePath()}/${getBinaryName(DEFAULT_FRIDA_INJECT)}"
    fun getActiveCliPath(): String = "${getBasePath()}/${getBinaryName(DEFAULT_FRIDA_CLI)}"
    fun getActiveScriptPath(): String = "${getBasePath()}/script.js"

    fun resolveRandomizedName(name: String): String {
        return when (name) {
            settings.randomizedServerName -> DEFAULT_FRIDA_SERVER
            settings.randomizedInjectName -> DEFAULT_FRIDA_INJECT
            settings.randomizedCliName -> DEFAULT_FRIDA_CLI
            else -> name
        }
    }

    fun writeStealthConfig() {
        try {
            val isStealth = settings.isStealthModeEnabled
            val serverName = getBinaryName(DEFAULT_FRIDA_SERVER)
            val port = getActivePort()
            val basePath = getBasePath()
            
            val config = """
                # Generated by ReShift
                STEALTH_MODE=${if (isStealth) 1 else 0}
                FRIDA_SERVER_NAME="$serverName"
                FRIDA_PORT=$port
                FRIDA_PATH="$basePath/$serverName"
            """.trimIndent()
            
            val tempFile = File(context.cacheDir, "stealth_config.sh")
            tempFile.writeText(config)
            
            ShellExecutor.executeSimple("mkdir -p $BASE_STEALTH_PATH && cat ${tempFile.absolutePath} > $BASE_STEALTH_PATH/config.sh && chmod 644 $BASE_STEALTH_PATH/config.sh", useRoot = true)
            ShellExecutor.executeSimple("mkdir -p $LEGACY_BASE_PATH && cat ${tempFile.absolutePath} > $LEGACY_BASE_PATH/config.sh && chmod 644 $LEGACY_BASE_PATH/config.sh", useRoot = true)
            
            Log.d(TAG, "Config updated (Stealth=$isStealth): $serverName on port $port at $basePath")
        } catch (e: Exception) {
            Log.e(TAG, "Failed to write config", e)
        }
    }
}
